version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    expose:
      - 6379
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: '*****'
      MYSQL_PASSWORD: '*****'
      MYSQL_ROOT_PASSWORD: '*****'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/pessolatohenrique/Desktop/projects/mysql:/var/lib/mysql
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/home/pessolatohenrique/Desktop/projects/mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '****'
      MONGO_INITDB_ROOT_PASSWORD: '****'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my_topic:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
